### ISSUE TITLE
Save the list in mohsen's brain

### ISSUE THREAD

**Issue by matefh** [matefh/mohsen#4]
We need to store this list https://github.com/matefh/mohsen/blob/master/list.yml in mohsen's brain

**Comment by matefh** [comment]
@MohamedBassem

**Comment by matefh** [comment]
Do you think we should just read from file and save it in the brain? or just read from file and skip the brain?

**Comment by MohamedBassem** [comment]
Let's JSONify it and save it brain and then we won't need this file anymore
